module.exports = {
  CLARIFAI_KEY: process.env.CLARIFAI_KEY,
  ALGOLIA_APP_ID: process.env.ALGOLIA_APP_ID,
  ALGOLIA_ADMIN_API_KEY: process.env.ALGOLIA_ADMIN_API_KEY,
  ALGOLIA_TALENT_INDEX: process.env.ALGOLIA_TALENT_INDEX
}
